AllCops:
  NewCops: enable

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Lint/UselessSetterCall:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150
  AllowedPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
